### ISSUE TITLE
Option to clone repo?

### ISSUE THREAD

**Issue by gregrickaby** [WebDevStudios/generator-s#1]
Testing this out tonight and noticed the generator is grabbing from /app/src/templates (which is already out-of-date) instead of cloning directly from Github. Does this mean we need to ping @CamdenSegal or @bradp every time we push code to _s?

P.S. shouldn't Mr. Yeoman be saying "Welcome to the fantastic _s generator"? :smile: 

![screenshot 2015-04-13 22 59 26](https://cloud.githubusercontent.com/assets/200280/7130164/cd20c3be-e230-11e4-936f-74bd54b660e0.png)

Love ya, mean it!

**Comment by bradp** [comment]
Yeah, Camden and I talked about having it pull down _s and run the build script when using it, we can for sure change it over to that pretty simply. 

Brad Parbs

**Comment by gregrickaby** [comment]
I we clone, will that introduce the "git errors" like before?

**Comment by bradp** [comment]
No, it won't.

**Comment by gregrickaby** [comment]
It did.

**Comment by bradp** [comment]
Fixed in e8de1d8031516cd1ebab94b36a692e9c639c6c20
